import { type GetStaticPropsResult } from 'next';
import Head from 'next/head';

import { graphqlClient } from '@/graphql/client/graphql.client';
import { GET_USERS } from '@/graphql/queries';
import { User } from '@/types';

export default function Home({ users }: { users: User[] }) {
  return (
    <>
      <Head>
        <title>MTH</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <pre>{JSON.stringify(users, null, 2)}</pre>
      </main>
    </>
  );
}

export async function getStaticProps(): Promise<
  GetStaticPropsResult<{ users: User[] }>
  // eslint-disable-next-line indent
> {
  const users = await graphqlClient
    .request<{ users: User[] }>(GET_USERS)
    .then(({ users }) => users);

  return {
    props: {
      users,
    },
  };
}
